parameters:
  cas_login_target: 'http://127.0.0.1:8000'
  cas_host: 'cas.u-picardie.fr'

l3_cas:
  host: 'cas.u-picardie.fr'                        # Cas Server
  path: ~                                             # App path if not in root (eg. cas.test.com/cas)
  port: 443                                       # Server port
  ca: false                                           # SSL Certificate
  handleLogoutRequest: true                           # Single sign out activation (default: false)
  casLogoutTarget: 'http://127.0.0.1:8000'      # Redirect path after logout
  force: true                                        # Allows cas check mode and not force, user : __NO_USER__ if not connected (If force false, Single sign out cant work).  force: false    