vich_uploader:
    db_driver: orm

    mappings:
        upload_csv:
            uri_prefix: /admin/csv/upload
            upload_destination: '%kernel.project_dir%/public/csv/upload'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true